### ISSUE TITLE
Multiple object tracking

### ISSUE THREAD

**Issue by nitish11** [jbhuang0604/CF2#4]
Hi, 

With respect to this video of[ walking people](https://drive.google.com/file/d/0B8-i_hZvGyZNbzE4LXVId0JJazg/view), could you use this model for tracking multiple people?

If yes, how can you do the same?

**Comment by hu5tao** [comment]
Hi, when l run this code 'run_tracker.m' just  in CPU. 
An error occurred：“img=imResample(img, net.meta.normalization.imageSize(1:2)) , net have non-exitent field meta  ”
please this  is  the reason why ? Just  can be run in GPU?

**Comment by shashikant-ghangare** [comment]
Change **net.meta.normalization.imageSize(1:2)** to **net.normalization.imageSize(1:2)** .

**Comment by NCJ9527** [comment]
Hi,when i run this code'tracker_ensemble.m'.An error occurred:When tap 'tracker_ensemble.m',output parameter positions not assigned.Please tell me the reason.Thank you.

**Comment by nitish11** [comment]
As I am not exploring this thread, I am closing the issue.
